[general]
altitude = 326.0

[i2c]
bus = 1

[doorbell]
bell_gpio = 23
button_gpio = 24

[linky]
server_port = 8100
serial_port = "/dev/ttyAMA0"
baudrate = 9600
bytesize = "SEVENBITS"
parity = "PARITY_EVEN"
stopbits="STOPBITS_ONE"

[ups]
ac220_gpio = 6
buzzer_gpio = 5

[mqtt]
host = "localhost"
port = 1883

[[logger]]

[logger.root]
level = "DEBUG"

[logger.domotik.bmp180]
level = "INFO"

[logger.domotik.doorbell]
level = "INFO"

[logger.domotik.linky]
level = "INFO"

[logger.domotik.ups]
level = "INFO"
