[doorbell]
bell_gpio = 23
button_gpio = 24

[linky]
server_port = 8080
serial_port = "/dev/ttyAMA0"
baudrate = 9600
bytesize = "SEVENBITS"
parity = "PARITY_EVEN"
stopbits="STOPBITS_ONE"

[logger]
linky = "DEBUG"
doorbell = "DEBUG"
