[doorbell]
bell_gpio = 23
button_gpio = 24

[general]
altitude = 326.0

[i2c]
bus = 1

[linky]
server_port = 8100
serial_port = "/dev/ttyAMA0"
baudrate = 9600
bytesize = "SEVENBITS"
parity = "PARITY_EVEN"
stopbits="STOPBITS_ONE"

[[logger]]

[logger.root]
level = "DEBUG"

[logger.domotik.linky]
level = "INFO"

[logger.domotik.doorbell]
level = "INFO"

[logger.domotik.bmp180]
level = "INFO"
