- id: sonner
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.bouton_de_sonnette
    to: 'on'
  action:
  - data:
      qos: 0
      retain: false
      topic: home/doorbell/bell
    action: mqtt.publish
  - metadata: {}
    data:
      message: On sonne à la porte
      target: fbarbenoire@gmail.com
      title: Ding dong !
    action: notify.email
  mode: single
- id: urgence
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt/0x847127fffe27cf5f/action
    payload: emergency
  action:
  - service: notify.email
    metadata: {}
    data:
      message: À l'aide
      target: fbarbenoire@gmail.com
      title: Urgence
  mode: single
